from typing import Protocol, Dict, Any

class ShortTermMemory(Protocol):
    def load(self) -> str: ...
    def upsert(self, question: str, answer: str) -> None: ...

class Repository(Protocol):
    def get_session_data(self, session_id: str) -> Dict[str, Any]: ...
    def upsert_session_data(self, session_id: str, data: Dict[str, Any]) -> None: ...